Sesia_Przestepne/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Sesia_Przestepne.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Sesia_Przestepne/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Sesia_Przestepne.Models;
using Sesia_Przestepne.Services.Interfaces;
using System;

namespace Sesia_Przestepne.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        
        private readonly ISearchLogService _searchLogService;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;


        [BindProperty]
        public Search NewSearch { get; set; }

        public IndexModel(ISearchLogService searchLogService ,ILogger<IndexModel> logger, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _searchLogService = searchLogService;
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public void OnGet() {
            
        }

        public IActionResult OnPost()
        {
            
            if (ModelState.IsValid)// ciekawostka musiałem dodać ? po typie string dla zmiennej Name, jest to dla tego, że jeśli nie podało się nazwy urztkownika 
            {
                var Data = HttpContext.Session.GetString("People");
                List<Search> People = new List<Search>();
                if (Data != null)
                    People = JsonConvert.DeserializeObject<List<Search>>(Data);
                
                NewSearch.IsLeap();

                People.Add(NewSearch);

                if (_signInManager.IsSignedIn(User))
                {
                    NewSearch.UserId = _userManager.GetUserId(User);
                    NewSearch.User = (IdentityUser?)_userManager.Users.Where(x=>x.Id == NewSearch.UserId).First();
                }

                NewSearch.SearchTime = DateTime.Now;

                _searchLogService.AddSearch(NewSearch);

                HttpContext.Session.SetString("People",
                JsonConvert.SerializeObject(People));
            }
            return Page();

        }
    }
}

Sesia_Przestepne/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Sesia_Przestepne.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Sesia_Przestepne/Pages/Saved.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Sesia_Przestepne.Models;
using System.Text.Json.Serialization;

namespace Sesia_Przestepne.Pages
{
    public class SavedModel : PageModel
    {
        public List<Search> People = new List<Search>();
        public void OnGet()
        {
            var Data = HttpContext.Session.GetString("People");
            if (Data != null)
                People = JsonConvert.DeserializeObject<List<Search>>(Data);
        }
    }
}

Sesia_Przestepne/Pages/SearchLog.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Sesia_Przestepne.Models;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Sesia_Przestepne.Services.Interfaces;

namespace Sesia_Przestepne.Pages
{
    [Authorize]
    public class SearchLogModel : PageModel
    {

        private readonly ISearchLogService _searchLogService;
        private readonly UserManager<IdentityUser> _userManager;


        public int CurrentPage { get; set; } = 1;
        public int PageAmount { get; set; } = 1;
        public int PageSize { get; set; } = 20;

        public SearchLogModel(ISearchLogService searchLogService, UserManager<IdentityUser> userManager)
        {
            _searchLogService = searchLogService;
            _userManager = userManager;
        }

        public List<Search> People { get; set; } = default!;

        public async Task<IActionResult> OnPostRemoveLogAsync(int id, int currentPage = 1)
        {
            //sprawdzamy, czy baza danych zawiera jakiekolwiek wartości
            if (await _searchLogService.IsPeopleNotNull())
            {
                //usuwamy wyszukanie o podanym id
                await _searchLogService.RemoveSearch(id, _userManager.GetUserId(User));

                PageAmount = await _searchLogService.GetPageAmount();

                currentPage = (currentPage > PageAmount) ? PageAmount : currentPage;

                await _searchLogService.GetCurrentPage(currentPage);
            }
            return Page();
        }

        public async Task OnGetAsync(int currentPage = 1)
        {
            if (await _searchLogService.IsPeopleNotNull())
            {
                PageAmount = await _searchLogService.GetPageAmount();

                currentPage = (currentPage > PageAmount) ? PageAmount : currentPage;

                People = await _searchLogService.GetCurrentPage(currentPage);
            }
        }

        public string GetUserName(string id)
        { 
            return (_userManager.Users.Any(x => x.Id == id)) ? _userManager.Users.Where(x => x.Id == id).FirstOrDefault().UserName : "";
        }
    }
}

Sesia_Przestepne/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="">
    <form method="post">
        <div class="form-group mb-3">
            <label asp-for="NewSearch.Name"></label>
            <input type="text" asp-for="NewSearch.Name" /><br />
            <span style="display: block; font-weight: bold" asp-validation-for="NewSearch.Name" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="NewSearch.Year"></label>
            <input type="number" asp-for="NewSearch.Year" /><br />
            <span style="display: block; font-weight: bold" asp-validation-for="NewSearch.Year" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Zatwierdź</button>
        @if (Model.NewSearch != null && ModelState.IsValid)
        {
            <div class="alert alert-success" style="display:block" role="alert">
                <span>
                    @if(Model.NewSearch.Name != null){
                        @Model.NewSearch.Name
                        @if (@Model.NewSearch.Name.Length > 0 && @Model.NewSearch.Name[Model.NewSearch.Name.Length-1] == 'a')
                        {
                            <span>urodziła</span>
                        }
                        else{
                            <span>urodził</span>
                        }
                        <span>się w</span>
                        @Model.NewSearch.Year
                        <span>roku.</span>
                    }
                   else{
                        <span>Rok </span>
                        @Model.NewSearch.Year
                    }
                     To
                    @if (!@Model.NewSearch.Leap??true)
                    {
                        <span>nie</span>
                    }
                    był rok przestępny.
                </span>
            </div>
        }
    </form>
</div>

Sesia_Przestepne/Pages/Saved.cshtml
@page
@model Sesia_Przestepne.Pages.SavedModel
@{
}
@if (Model.People != null)
{
    <p>
        @foreach(var p in Model.People)
            {<li>
                @p.Name
                ,
                @p.Year
                 - 
                 rok
                @if (!p.Leap??true)
                {
                    <span>nie</span>
                }
                przestępny
            </li>}
    </p>
}

Sesia_Przestepne/Pages/SearchLog.cshtml
@page
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model Sesia_Przestepne.Pages.SearchLogModel
@if (Model.People != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Imie
                </th>
                <th>
                    Sprawdzany rok
                </th>
                <th>
                    Przestępny
                </th>
                <th>
                    Data Wyszukiwania
                </th>
                <th>
                    Użytkownik ID
                </th>
                <th>
                    Użytkownik Nazwa
                </th>
                <th>
                    Usuń
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.People)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Year
                    </td>
                    <td>
                        @item.Leap
                    </td>
                    <td>
                        @item.SearchTime
                    </td>
                    <td>
                        @item.UserId
                    </td>
                    <td>
                        @Model.GetUserName(item.UserId)
                    </td>
                    <td>
                       @if (UserManager.GetUserId(User) == item.UserId) {
                            <form method="post" asp-page-handler="RemoveLog" asp-route-id="@item.Id" asp-route-currentPage="@Model.CurrentPage">
                                <button type="submit">usuń</button>
                            </form>
                        }
                        else{
                            <input type="button" value="usuń" disabled="disabled">
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div style="font-size: 20px; font-weight: bold; text-align: center;">
        @if(Model.PageAmount>1)
        @for (var i = 1; i <= Math.Ceiling((double)Model.PageAmount); i++)
        {
            if (i == Model.CurrentPage)
            {
                <text>@i</text>
            }
            else
            {
                <a asp-page="./SearchLog" asp-route-currentPage="@i">@i</a>
            }
        }
    </div>
}